### ISSUE TITLE
HTML page 

### ISSUE THREAD

**Issue by angipp01** [REHolt/Garage-Door#4]
Sorry to bug you again.  I have some vacation time during this Christmas break.  I bought 18/2 wiring to connect to the door contacts and the module.  I am having difficultly implementing a separate webpage that has buttons for triggering Left and Right garage doors.  Also to 'Get' status of the Left and Right.

Since the unit you have designed is functional for only Android.  Creating a separate web pages would be the work around for Apple & Blackberry products.

I have been messing around with it and don't get it.   I am wondering if you can assist me.  
Cheers. Ang.

https://youtu.be/ONKM5lSthNY

**Comment by angipp01** [comment]
I think I got it...  I will test it out on Sunday or Monday.

else if (req.indexOf("/Full") != -1){
    client.flush();
    client.println("HTTP/1.1 200 OK");
   client.println("Content-Type: text/html");
   client.println(""); //  do not forget this one
   client.println("<!DOCTYPE HTML>");
   client.println("<html>");
   

    String s1 = "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n\r\n<html>\r\nGarage Door 1 is ";
    s1 += (Door1_Status);
    s1 += "</html>\n";
    client.print(s1);
   
   String s2 = "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n\r\n<html>\r\nGarage Door 2 is ";
    s2 += (Door2_Status);
    s2 += "</html>\n";
    client.println(s2);
    delay(1);

   client.println("<br><br>");
  client.println("Click <a href=\"/gpio/1\">here</a> trigger Right Garage door<br>");
  client.println("Click <a href=\"/gpio/2\">here</a> trigger Left Garage door<br>");
  client.println("</html>");
   
   Serial.println("Client disonnected");

**Comment by angipp01** [comment]
Well I got the web page working.   Now we will have the ability to control this universally Example: PC, Apple, Lynx.  

I am having 1 issue.  I think it is a simple one.   I don't know how to tell Arduino to return to '/Full once Gpio/3 has finished it sequence? 

Can you help me on this one.  I have googled it, but unsuccessful.

else if (req.indexOf("/Full") != -1){  //brings to Webpage 192.168.1.59/Full
   client.flush();
   client.println("HTTP/1.1 200 OK");
   client.println(""); //  do not forget this one
   client.println("<html>");
   client.println("<HEAD>");  
   client.println("<meta name='apple-mobile-web-app-capable' content='yes' />");
   client.println("<meta name='apple-mobile-web-app-status-bar-style' content='blue-translucent' />");
   client.println("<TITLE>Garage Door</TITLE>");
   client.println("</HEAD>");
   client.println("<BODY>");
      

    String s1 = "Garage Door 1 is ";
    s1 += (Door1_Status);
    s1 += "</html>\n";
    client.println(s1);
   
   client.println("<br><br>");
   
   String s2 = "Garage Door 2 is ";
    s2 += (Door2_Status);
    s2 += "</html>\n";
    client.println(s2);
    delay(1);

  client.println("<br><br>");
  client.println("<h1>Click <a href=\"/gpio/3\">here</a> trigger Right Garage door<br></h1>");
  client.println("<br><br>");
  client.println("<h1>Click <a href=\"/gpio/4\">here</a> trigger Left Garage door<br></h1>");  //I haven't created /gpio/4  yet.
  
  client.println("</BODY>");
  client.println("</html>");
   
   Serial.println("Client disonnected");

    Serial.print("Door No. ");
    Serial.println(Door);
    Serial.println(s);}

else if (req.indexOf("/gpio/3") != -1){
    val = 1;
    Door = 1;
//    Serial.print("Door No. ");
//   Serial.println(Door);
    digitalWrite(Door1trigger, val);
    delay (500);
    val = 0;
    digitalWrite(Door1trigger, val);
    client.flush();
    
    delay(1);
    Serial.println("Client disonnected");}

**Comment by REHolt** [comment]
Hi angipp01;

Sorry if it seems that I have been ignoring you, but I have been traveling a lot for work lately and I experienced a computer crash, so have not been active on this site lately. In fact I am installing software on my new computer today so that I can get back up and running.

I'm glad to hear you got something working. I will take a look at your question and see if I can help out with your current problem. It looks like you have gotten way past my level of expertise, as I have never attempted anything like what you are doing. Also, I am a little rusty since I haven't messed with any of this in over a month.

**Comment by angipp01** [comment]
I have you just a posted part of the code. (this is because the rest of the code is the same as yours)   
I have provided the full attachment notepad.

After this is done.  I am going to control this from anywhere (not just locally in your network.  Therefore, you can check your status/control at work by looking-up on a webpag
[Jan 2017 sketch.txt](https://github.com/REHolt/Garage-Door-Controller/files/722059/Jan.2017.sketch.txt)
e.   I think I can do this using free DDNS providers  (no-ip.com or dnsdynamic.org/).  Most routers already have this build into the firmware.

**Comment by REHolt** [comment]
angipp01;

I read through the code and I'm not sure what you are asking for help with. I'm not familiar with web application programming. It seems that you should just be able to include a statement that sets the index back to "1".

*Note: I was typing this and just saw you new post. I downloaded the full file and will take a look to see if I can better understand it.

**Comment by angipp01** [comment]
When I click the first link it triggers the relay (Great!) but brings me to a blank page, but I want it to go back to /Full.

**Comment by REHolt** [comment]
I haven't had much time today, but when I tried to compile the file you sent me, I get errors. It says there is a problem with an "else" statement. Is this the same file you have been working with?

**Comment by angipp01** [comment]
My mistake   I found i left an extra "}" while troubleshooting...

There is another .txt.

[Jan 2017 sketch.txt](https://github.com/REHolt/Garage-Door-Controller/files/722428/Jan.2017.sketch.txt)

**Comment by REHolt** [comment]
That's what I thought, thanks!

**Comment by REHolt** [comment]
That worked, it compiles now. I will need to put together another part to test on.

**Comment by REHolt** [comment]
how do I bring up the web page? I thought it was to just access the default ip address of the part. but I get an error.

**Comment by REHolt** [comment]
OK, I got it to work. I just needed to reset the device. I had forgotten to capitalize "/Full" and it got hung up.

Now I can see if I can get it to work.

**Comment by angipp01** [comment]
Ok perfect.
I designed it basic right now.  I had to increase the font because it was very small to see on the Iphone. 
Later I will replace the link for a button.

**Comment by angipp01** [comment]
Once I have it accessible to the internet.  I think I will secure the webpage to be accessible using username and password.  Therefore, if someone hacks into the Garage open from Russia and I would hear the door open & closing while I am sleeping.

**Comment by REHolt** [comment]
Try copying the code for "/Full" to the bottom of gpio/3. this will cause it to refresh the webpage after activating the door.

else if (req.indexOf("/gpio/3") != -1){
    val = 1;
    Door = 1;
  Serial.print("Door No. ");
  Serial.println(Door);
    digitalWrite(Door1trigger, val);
    delay (500);
    val = 0;
    digitalWrite(Door1trigger, val);
    client.flush();
    
    delay(1);
    Serial.println("Client disonnected");

    
    Serial.print("Door No. ");
    Serial.println(Door);
    Serial.println(s);
     client.println("HTTP/1.1 200 OK");
   client.println(""); //  do not forget this one
   client.println("<html>");
   client.println("<HEAD>");  
   client.println("<meta name='apple-mobile-web-app-capable' content='yes' />");
   client.println("<meta name='apple-mobile-web-app-status-bar-style' content='blue-translucent' />");
   client.println("<TITLE>Garage Door</TITLE>");
   client.println("</HEAD>");
   client.println("<BODY>");
      

    String s1 = "Garage Door 1 is ";
    s1 += (Door1_Status);
    s1 += "</html>\n";
    client.println(s1);
   
   client.println("<br><br>");
   
   String s2 = "Garage Door 2 is ";
    s2 += (Door2_Status);
    s2 += "</html>\n";
    client.println(s2);
    delay(1);

  client.println("<br><br>");
  client.println("<h1>Click <a href=\"/gpio/3\">here</a> trigger Right Garage door<br></h1>");
  client.println("<br><br>");
  client.println("<h1>Click <a href=\"/gpio/4\">here</a> trigger Left Garage door<br></h1>");  //I haven't created /gpio/4  yet.
  
  client.println("</BODY>");
  client.println("</html>");
   
   Serial.println("Client disonnected");

    Serial.print("Door No. ");
    Serial.println(Door);
    Serial.println(s);
       
    }

**Comment by REHolt** [comment]
Also, am I right that the code for door 2 isn't in the file yet?

**Comment by REHolt** [comment]
I tested it with the web page and with the app and it seems to work. After clicking on "Right Door", the relay triggers and the webpage updates back to the full page with status and buttons.

**Comment by REHolt** [comment]
To make the code a little smaller and more compact, you might be able to put the "Web Page Build routine" in a subroutine that you can call when needed. Seems like I have even seen a method where you can build the web page in HTML and store it as data in the ESP8266 SPIFFS memory. If I have some time the next couple of days, I may look into that. 

Let me know what progress you make. If you are able to implement buttons and a password it would be nice. This would actually help solve one of the problems I am having with accessing my home control stuff with something other than an Android app.

**Comment by angipp01** [comment]
ok this is great.     https://www.youtube.com/watch?v=FOyQWgwXccA
Even supplies the codes.  

How to implement  to the /Full.html. I have no idea.  I will work on this during the weekend.

**Comment by angipp01** [comment]
Oh you have commented on a subroutine.  All this is over my head.  I just know how to create a basic site, and to do basic functions.  It took me forever to figure you your code. I do get excited when I get it working.  It is all trial and error for me. Over and over again.   I will try to impalment this secure http. sometime this week.

**Comment by REHolt** [comment]
Did you implement the change I suggested? I implemented it on ,y system and it seems to work. It doesn't do exactly what you wanted, but it does provide the desired results.

**Comment by angipp01** [comment]
No I haven't implemented because I won't know how too.

**Comment by REHolt** [comment]
I copied a portion of the code into my post so you could see what I did. All you have to do is cut and past a portion of the code you already have into a another part of your file. Updated file is attached.


[UniversalGarageDoorOpener.txt](https://github.com/REHolt/Garage-Door-Controller/files/725612/UniversalGarageDoorOpener.txt)

**Comment by angipp01** [comment]
Ok, I will try to check it out tonight (working late) if not I will check it out Wednesday (no plans Wednesday).

**Comment by angipp01** [comment]
I installed your scripted.  I said, wow you did it.  Then I looked at the URL and noticed you have repeated the HTML coding to the GPIO3 page. (It works)  I was thinking about this also, but then I would repeat it on the same to GPIO4 page.   I was thinking there must be a why just to return to the /Full page with a 1000 delay (1sec delay).  Doing this will make the code shorter.  I still can't believe when I googled for this I can't find a solution.  I thought it was a meta refresh command but i was wrong.

**Comment by angipp01** [comment]
I have an idea, but now thinking it is not possible.   

Do I have to have it go to another webpage?  Do the Link need to go to GPIO3 to have the relay get triggered?  

I have thrown this out to the Arduino forum, but still no solution. 

http://forum.arduino.cc/index.php?topic=449355.msg3100563#msg3100563

**Comment by REHolt** [comment]
I was thinking the same thing last night. I was hoping to experimenting with it, and maybe a couple of other ideas. I agree there should be a way to make it work. In the meantime, this solution will at least get it going.

**Comment by angipp01** [comment]
I think i am going to try this. 

http://forum.arduino.cc/index.php?topic=165982.0

**Comment by REHolt** [comment]
Looks like it just might work.

**Comment by angipp01** [comment]
I have tried this but doesn't work. I created a button.   Still brings me to a dead page


  client.println("<br><br>");
  client.println("<h1>Click <a href=\"/gpio/3\">here</a> trigger Right Garage door<br></h1>");
  client.println("<input type=button value=ON onmousedown=location.href='/?on4'>"); 
  client.println("<br><br>");
  client.println("<h1>Click <a href=\"/gpio/4\">here</a> trigger Left Garage door<br></h1>");  //I haven't created /gpio/4  yet.
  
  client.println("</BODY>");
  client.println("</html>");
   
   Serial.println("Client disonnected");
   client.stop();

    Serial.print("Door No. ");
    Serial.println(Door);
    Serial.println(s);}


else if (readString.indexOf('4') >0){//checks for 4
          digitalWrite(Door1trigger, val);
           delay (500); 
           val = 0; 
           digitalWrite(Door1trigger, val);
           client.flush(); 
           delay(1);           
           
            readString="";
}

**Comment by angipp01** [comment]
I am reading my thread. They are saying to redirect using the meta.  But not working. 

For example I have tried this and put a delay on it, but still end up at a dead page

else if (req.indexOf("/gpio/3") != -1){
    val = 1;
   // Door = 1;
  //Serial.print("Door No. ");
  //Serial.println(Door);
    digitalWrite(Door1trigger, val);
    delay (500);
    val = 0;
    digitalWrite(Door1trigger, val);
    client.flush();
    delay(3000);
    Serial.print("<meta http-equiv='Refresh' content='1; url=http://google.com'> ") ; 
    
    Serial.println("Client disonnected");

**Comment by angipp01** [comment]
got it to work 
it redirects back to the Full.html page.

Next I will find out a way to use username and password.

[garage door test.txt](https://github.com/REHolt/Garage-Door-Controller/files/737142/garage.door.test.txt)

**Comment by REHolt** [comment]
Cool! I will have to give it a try. Can you use it from outside your local network?

**Comment by angipp01** [comment]
No, I haven't accessed it using external (but this should not be an issue.  I have developed Webpages years ago to access it externally, uding DDNS free services.)

Would you know how to use some this code and use it to the our code.

http://aquatictechtank.net/viewtopic.php?f=37&t=185&p=530#p530

**Comment by REHolt** [comment]
No, I might be able to figure it out, ignition had the time, but lately I have had a lot of other distractions. I haven't had much time to focus on software. I have been traveling with work and even some with family. It makes it hard to find time for hobbies.

**Comment by angipp01** [comment]
No problem. You did a lot.  I will keep you updated.

**Comment by angipp01** [comment]
So, I have tossed a side having this accessible to the internet.   I have my friends warned me against it, since Arduino does not support HTTPS, and I will have port open on my Network.

I am currently working on your code in my free time.  I am trying to get the SMS text message to work.  I have tested out the URL and it does send me a text message, although the Scripting doesn't trigger the URL to send me a text message.    I have found something missing in the script, and I fixed it.  Although something is still missing because it still not is triggering the URL.
  I will update you later and hopfully I can get it to work.

**Comment by angipp01** [comment]
[garage door sms.txt](https://github.com/REHolt/Garage-Door-Controller/files/752024/garage.door.sms.txt)

I have added a few code that you were missing in the SMS section.   
I have also updated the Finger print SHA-1 of the https://ifttt.com/  (Hammer site was a little out of date).  I have it set for 1min wait and to texted me.  

Nope still doesn't work?  My link is working that is pasted in the Key.h tab, but something is missing...

**Comment by REHolt** [comment]
Noticed you just closed this. Did you solve the problem? 

I just hit a huge milestone with one of my other projects and was going to try and look at this some this week. Some of what you are wanting to d will help me with the software for the other project so I plan to try and implement it and getting it working.
